### ISSUE TITLE
Post Example Config.json

### ISSUE THREAD

**Issue by nctiggy** [EMC-Underground/pnwreport#1]
config.json.example???

This is rough without the URL's, what options might exist?

**Comment by bkvarda** [comment]
Info is read from config/config.json. Format is kind of temporary but it is as below, I'll e-mail you with the URLs. 

{
        "domain" : "thisisthedomain",
        "username" : "your_nt_id",
        "password" : "your_nt_pw",
        "srurl1" : "first_part_of_sr_url",
        "srurl2" : "second_part_of_sr_url"
        "installurl1" : "first_part_of_install_url",
        "installurl2" : "second_part_of_install_url"
}
